import { HTMLPropsMixin } from '@html-props/core';
import { Button } from '@html-props/built-ins';

/**
 * Props interface for ButtonComponent
 */
interface ButtonComponentProps {
  label?: string;
  color?: string;
}

/**
 * ButtonComponent component
 * Generated by HTML Props Builder
 */
export class ButtonComponent extends HTMLPropsMixin<typeof HTMLElement, ButtonComponentProps>(HTMLElement) {
  static props = {
    label: { type: String, default: '' },
    color: { type: String, default: '' },
  };

  declare label: string;
  declare color: string;

  render() {
    return new Button({
      textContent: this.label || 'Button',
      style: {
        padding: '0.5rem 1rem',
        borderRadius: '0.25rem',
        border: 'none',
        backgroundColor: this.color || '#38bdf8',
        color: '#0f172a',
        cursor: 'pointer',
        fontWeight: '600',
      },
    });
  }
}

ButtonComponent.define('button-component');

